services:
  sqlpage:
    build: .
    ports: ["8080:8080"]
    volumes: [".:/var/www"]
    depends_on: [postgres]
    environment:
      - DATABASE_URL=postgres://root:root@postgres/sqlpage
  postgres:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sqlpage